### PR TITLE
(Update) MassPM Function

### PR DESCRIPTION
**Pull request by VerioPL**
Please make some review is it okay. Mass PM's are now handled as a queue job.

TODO: Configuration of queue settings

### CODE REVIEW

**Comment by VerioPL** [comment]
If accepted please close assigned ticket #238 .

**Comment by VerioPL** [comment]
On my test lab (100k users) with redis queue driver now it is working much more better. In a few (less than 5) seconds foreach in controller is makings jobs, then jobs are processing in background.

**Comment by HDVinnie** [comment]
Why are making another jobs migration? It already exists.
https://github.com/HDInnovations/UNIT3D/blob/master/database/migrations/2017_12_10_020753_create_jobs_table.php

**Comment by HDVinnie** [comment]
If you would please spit this into 4 separate PR's. There to much going on in a single PR that are not related to each other. I suggest making the following separate ones.

```
Title: (Update) MassPM Function
Description: Change MassPM Function to use a queue job (fix for #238)
Tags: Enhancement Tag
```

```
(Update) Torrent Blades Lang 
Description: Torrent blades multilingual support EN/PL
Tags: Translation Tag
```

```
Title: (Fix) 404 in url to TMDB
Description: tmdb/movie/id not tmdb/movies/id
```

```
Title: (Fix) Report Controller
Description: revert variable change from commit 
```


One pull request per feature/fix/update/etc - If you want to do more than one thing in separate "systems", send multiple pull requests.

**Pull request closed without merging**
